# Cortar arboles (trim tree depth) config

paths:
  input_dir: '/data/Output/TreesSplines' 
  output_dir: '/data/Output/TreesSplines_100depth'

params:
  max_depth: 100
  k: 39
  input_mode: post_order
  output_mode: pre_order
  glob: "*.npy"
  overwrite: false
  log_every: 1
