# Dataset preparation config

paths:
  input: /data/Output/TreesSplines_100depth
  output: /data/Output/TreesSplines_100depth_prepared

params:
  k: 39
  mode: pre_order
  n_rotations: 10
  pattern: "*.npy"
  overwrite: false
  seed: 125
  spline_samples: 50
  spline_smooth: 0.0000001
  enable_rotation: false
  enable_scaling: true
  refit_splines: false
  erase_output: true
