# Dataset split config

paths:
  input: DemoOutput/TreesSplines_20depth_prepared
  output: DemoOutput/TreesSplines_20depth_prepared

params:
  train: 0.8
  val: 0.1
  test: 0.1
  seed: 42
  pattern: "*.npy"
  move: false
