# Dataset split config

paths:
  input: /data/Output/TreesSplines_100depth_prepared
  output: /data/Output/TreesSplines_100depth_prepared

params:
  train: 0.8
  val: 0.1
  test: 0.1
  seed: 42
  pattern: "*.npy"
  move: false
