paths:
  input_dir: DemoOutput/TreesSplines_20depth_prepared/train
  output_dir: DemoOutput/TreesSplines_20depth_tokens/train
  model_checkpoint: /home/sukin707/VesselGPT/Stage1_New/Stage1_New/output_02/checkpoint-epoch1000.pth

params:
  k: 39
  device: 0
  pattern: "*.npy"
  zero_threshold: 0.001
  null_id: 258
  add_bos_eos: false
  bos_id: 256
  eos_id: 256
  overwrite: false
  strict_load: true

model:
  in_dim: 39
  n_embed: 256
