paths:
  input_dir: /data/Output/TreesSplines_k_count_150depth_prepared/val
  output_dir: /data/Output/TreesSplines_k_count_150depth_tokens/val
  model_checkpoint: /data/Output/Result/Stage1_New/VesselGPT_VQVAE_DGX_07/best-model-stage1.pth

params:
  k: 39
  mode: pre_order_kdir
  device: 0
  pattern: "*.npy"
  zero_threshold: 0.001
  null_id: 258
  add_bos_eos: false
  bos_id: 256
  eos_id: 256
  overwrite: false
  strict_load: true

model:
  in_dim: 40
  n_embed: 256
  hidden_size: 512
  num_hidden_layers: 6
  num_attention_heads: 8
  intermediate_size: 1536
  quant_factor: 0
  face_quan_num: 16
  neg: 0.2
  INaffine: false
  zquant_dim: 64
  quantization_mode: factorized
  factor_count: 4
  factor_dim: 128
  factor_proj: linear_shared
