paths:
  input_dir: /data/Output/TreesSplines_k_count_150depth_prepared/test/
  split_file_list: null
  root_dir: null
  p: null
  output_dir: /data/Output/Result/Stage1_New/VesselGPT_VQVAE_DGX_07/reconstructions_stage1
  compare_original: /home/sukin707/VesselGPT/Stage1_New/Stage1_New/reconstructions_stage1/input_epoch_721_batch_0_sample_8.npy
  compare_generated: /home/sukin707/VesselGPT/Stage1_New/Stage1_New/reconstructions_stage1/recon_epoch_721_batch_0_sample_8.npy

params:
  mode: pre_order_kdir
  visualize_mode: pre_order_kdir
  k: 39
  batch_size: 1
  shuffle: true
  threshold: 0.01 
  sample_limit: null
  device: 0
  seed: 12
  apply_threshold: false
  run_reconstruction: true
  run_compare: false
  run_visualize: false

model:
  type: vocaset
  checkpoint: /data/Output/Result/Stage1_New/VesselGPT_VQVAE_DGX_07/best-model-stage1.pth
  in_dim: 40
  hidden_size: 512
  num_hidden_layers: 6
  num_attention_heads: 8
  intermediate_size: 1536
  window_size: 1
  quant_factor: 0
  face_quan_num: 16
  neg: 0.2
  INaffine: false
  n_embed: 256
  zquant_dim: 64
  quantization_mode: factorized
  factor_count: 4
  factor_dim: 128
  factor_proj: linear_shared
  use_k_head: false
  k_loss_weight: 1.0
  # k_classes: 4
  emma:
    hidden_dim: 512
    codebook_size: 2048
