paths:
  train_dir: /data/Output/TreesSplines_k_count_150depth_tokens/train
  val_dir: /data/Output/TreesSplines_k_count_150depth_tokens/val
  output_dir: /data/Output/VesselGPT_GPT2_DGX_07
  best_model_dir: /data/Output/VesselGPT_GPT2_DGX_07/best-gpt2

params:
  vocab_size: 259
  max_size: 2258
  pad_token: 257
  eos_token: 256
  epochs: 50000
  lr: 0.0009
  batch_size: 128
  shuffle: false
  warmup_steps: 0
  scheduler: linear
  seed: 12
  device: 0
  log_every: 1
  track_token_usage: false
  token_usage_exclude_ids: []
  mem_check_enabled: true
  mem_check_every: 1
  mem_check_samples: 16
  mem_check_max_new_tokens: 512
  mem_check_do_sample: true
  mem_check_temperature: 1.0
  mem_check_top_k: 50
  mem_check_top_p: 0.95
  mem_check_num_beams: 1

model:
  n_embd: 512
  n_layer: 6
  n_head: 8

wandb:
  enabled: true
  project: gpt2
  #entity: vesselgpt
  mode: online
  run_name: VesselGPT_GPT2_DGX_07
